#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define CPU_RATE 500 

#define TIMER_RATE 60
#define TIMER_TIME 1000.0f / TIMER_RATE

#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32

#define PIXEL_WIDTH SCREEN_WIDTH/CHIP8_WIDTH
#define PIXEL_HEIGHT SCREEN_HEIGHT/CHIP8_HEIGHT
