#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define CPU_RATE 500
#define CPU_TIME 1000.0f / CPU_RATE

#define TIMER_RATE 60
#define TIMER_TIME 1000.0f / TIMER_RATE

#define PIXEL_WIDTH SCREEN_WIDTH/64
#define PIXEL_HEIGHT SCREEN_HEIGHT/32
